/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: s3_packet_header.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "s3_packet_header.pb-c.h"
void   s3_packet_header__init
                     (S3PacketHeader         *message)
{
  static const S3PacketHeader init_value = S3_PACKET_HEADER__INIT;
  *message = init_value;
}
size_t s3_packet_header__get_packed_size
                     (const S3PacketHeader *message)
{
  assert(message->base.descriptor == &s3_packet_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t s3_packet_header__pack
                     (const S3PacketHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &s3_packet_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t s3_packet_header__pack_to_buffer
                     (const S3PacketHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &s3_packet_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
S3PacketHeader *
       s3_packet_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (S3PacketHeader *)
     protobuf_c_message_unpack (&s3_packet_header__descriptor,
                                allocator, len, data);
}
void   s3_packet_header__free_unpacked
                     (S3PacketHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &s3_packet_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor s3_packet_header__field_descriptors[3] =
{
  {
    "pcode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(S3PacketHeader, pcode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(S3PacketHeader, session_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_len",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(S3PacketHeader, data_len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned s3_packet_header__field_indices_by_name[] = {
  2,   /* field[2] = data_len */
  0,   /* field[0] = pcode */
  1,   /* field[1] = session_id */
};
static const ProtobufCIntRange s3_packet_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor s3_packet_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "S3PacketHeader",
  "S3PacketHeader",
  "S3PacketHeader",
  "",
  sizeof(S3PacketHeader),
  3,
  s3_packet_header__field_descriptors,
  s3_packet_header__field_indices_by_name,
  1,  s3_packet_header__number_ranges,
  (ProtobufCMessageInit) s3_packet_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
